In [66]:
import pandas as pd
data={
    "Name":['Rahul','PRIYA','arjun','Sneha','rahul','Akhil',None,'Meera','PRIYA'],
    'Age':['22','23',None,'21','22','24','25','23','23'],
    'City':['kochi','Kochi','KOCHI','Trivandrum',None,'kochi','Calicut','CALICUT','Kochi'],
    'Course':['Data Science','data science','DATA SCIENCE','Python',None,'Python','Data Science','python','data science'],
    'Salary':['25000','30000','28000',None,'25000','32000','35000','30000','30000'],
    'Join_Date':['2025-01-10','15/01/2025','2025-02-05',None,'2025-01-10','20/02/2025','2025-03-01','invalid','15/01/2025']
    }
df=pd.DataFrame(data)
df

    Name  Age        City        Course Salary   Join_Date
0  Rahul   22       kochi  Data Science  25000  2025-01-10
1  PRIYA   23       Kochi  data science  30000  15/01/2025
2  arjun  NaN       KOCHI  DATA SCIENCE  28000  2025-02-05
3  Sneha   21  Trivandrum        Python    NaN         NaN
4  rahul   22         NaN           NaN  25000  2025-01-10
5  Akhil   24       kochi        Python  32000  20/02/2025
6    NaN   25     Calicut  Data Science  35000  2025-03-01
7  Meera   23     CALICUT        python  30000     invalid
8  PRIYA   23       Kochi  data science  30000  15/01/2025

In [67]:
#1. string cleaning
df['Name']=df['Name'].str.strip().str.title()
df['City']=df['City'].str.strip().str.title()
df['Course']=df['Course'].str.strip().str.title()

In [68]:
df

    Name  Age        City        Course Salary   Join_Date
0  Rahul   22       Kochi  Data Science  25000  2025-01-10
1  Priya   23       Kochi  Data Science  30000  15/01/2025
2  Arjun  NaN       Kochi  Data Science  28000  2025-02-05
3  Sneha   21  Trivandrum        Python    NaN         NaN
4  Rahul   22         NaN           NaN  25000  2025-01-10
5  Akhil   24       Kochi        Python  32000  20/02/2025
6    NaN   25     Calicut  Data Science  35000  2025-03-01
7  Meera   23     Calicut        Python  30000     invalid
8  Priya   23       Kochi  Data Science  30000  15/01/2025

In [69]:
#2. finding no.of missing values in each columns
df.isnull().sum()

Name         1
Age          1
City         1
Course       1
Salary       1
Join_Date    1
dtype: int64

In [70]:
#filling missed age and salary with using appropriate statistical value
#Here age and salary are in string format so to fill these 2 first convert it to numeric
df['Age']=pd.to_numeric(df['Age'])

In [71]:
df['Salary']=pd.to_numeric(df['Salary'])

In [72]:
df['Age']=df['Age'].fillna(df['Age'].mean())

In [73]:
df['Salary']=df['Salary'].fillna(df['Salary'].mean())

In [74]:
df

    Name     Age        City        Course   Salary   Join_Date
0  Rahul  22.000       Kochi  Data Science  25000.0  2025-01-10
1  Priya  23.000       Kochi  Data Science  30000.0  15/01/2025
2  Arjun  22.875       Kochi  Data Science  28000.0  2025-02-05
3  Sneha  21.000  Trivandrum        Python  29375.0         NaN
4  Rahul  22.000         NaN           NaN  25000.0  2025-01-10
5  Akhil  24.000       Kochi        Python  32000.0  20/02/2025
6    NaN  25.000     Calicut  Data Science  35000.0  2025-03-01
7  Meera  23.000     Calicut        Python  30000.0     invalid
8  Priya  23.000       Kochi  Data Science  30000.0  15/01/2025

In [75]:
#filling missing city with 'unknown'
df['City']=df['City'].fillna('Unknown')

In [76]:
df

    Name     Age        City        Course   Salary   Join_Date
0  Rahul  22.000       Kochi  Data Science  25000.0  2025-01-10
1  Priya  23.000       Kochi  Data Science  30000.0  15/01/2025
2  Arjun  22.875       Kochi  Data Science  28000.0  2025-02-05
3  Sneha  21.000  Trivandrum        Python  29375.0         NaN
4  Rahul  22.000     Unknown           NaN  25000.0  2025-01-10
5  Akhil  24.000       Kochi        Python  32000.0  20/02/2025
6    NaN  25.000     Calicut  Data Science  35000.0  2025-03-01
7  Meera  23.000     Calicut        Python  30000.0     invalid
8  Priya  23.000       Kochi  Data Science  30000.0  15/01/2025

In [77]:
#filling missing course with 'Not Specified'
df['Course']=df['Course'].fillna('Not Specified')

In [78]:
df

    Name     Age        City         Course   Salary   Join_Date
0  Rahul  22.000       Kochi   Data Science  25000.0  2025-01-10
1  Priya  23.000       Kochi   Data Science  30000.0  15/01/2025
2  Arjun  22.875       Kochi   Data Science  28000.0  2025-02-05
3  Sneha  21.000  Trivandrum         Python  29375.0         NaN
4  Rahul  22.000     Unknown  Not Specified  25000.0  2025-01-10
5  Akhil  24.000       Kochi         Python  32000.0  20/02/2025
6    NaN  25.000     Calicut   Data Science  35000.0  2025-03-01
7  Meera  23.000     Calicut         Python  30000.0     invalid
8  Priya  23.000       Kochi   Data Science  30000.0  15/01/2025

In [79]:
#3. find duplicate rows
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8     True
dtype: bool

In [80]:
#counting no.of duplicated rows
df.duplicated().sum()

np.int64(1)

In [81]:
#removing all duplicate rows
df.drop_duplicates(inplace=True)
df

    Name     Age        City         Course   Salary   Join_Date
0  Rahul  22.000       Kochi   Data Science  25000.0  2025-01-10
1  Priya  23.000       Kochi   Data Science  30000.0  15/01/2025
2  Arjun  22.875       Kochi   Data Science  28000.0  2025-02-05
3  Sneha  21.000  Trivandrum         Python  29375.0         NaN
4  Rahul  22.000     Unknown  Not Specified  25000.0  2025-01-10
5  Akhil  24.000       Kochi         Python  32000.0  20/02/2025
6    NaN  25.000     Calicut   Data Science  35000.0  2025-03-01
7  Meera  23.000     Calicut         Python  30000.0     invalid

In [82]:
#display cleaned dataframe
df

    Name     Age        City         Course   Salary   Join_Date
0  Rahul  22.000       Kochi   Data Science  25000.0  2025-01-10
1  Priya  23.000       Kochi   Data Science  30000.0  15/01/2025
2  Arjun  22.875       Kochi   Data Science  28000.0  2025-02-05
3  Sneha  21.000  Trivandrum         Python  29375.0         NaN
4  Rahul  22.000     Unknown  Not Specified  25000.0  2025-01-10
5  Akhil  24.000       Kochi         Python  32000.0  20/02/2025
6    NaN  25.000     Calicut   Data Science  35000.0  2025-03-01
7  Meera  23.000     Calicut         Python  30000.0     invalid

In [83]:
#4. datatype conversion
df['Age']=pd.to_numeric(df['Age'])

In [84]:
df['Salary']=pd.to_numeric(df['Salary'])

In [85]:
df.dtypes

Name             str
Age          float64
City             str
Course           str
Salary       float64
Join_Date        str
dtype: object

In [86]:
# Handling the invalid date without any error
df['Join_Date']=pd.to_datetime(df['Join_Date'],errors='coerce',dayfirst=True)
# This is used because error='coerce converts invalid dates to 'NaT' or 'NaN' which is useful before filling the missing values.

In [87]:
df

    Name     Age        City         Course   Salary  Join_Date
0  Rahul  22.000       Kochi   Data Science  25000.0 2025-10-01
1  Priya  23.000       Kochi   Data Science  30000.0        NaT
2  Arjun  22.875       Kochi   Data Science  28000.0 2025-05-02
3  Sneha  21.000  Trivandrum         Python  29375.0        NaT
4  Rahul  22.000     Unknown  Not Specified  25000.0 2025-10-01
5  Akhil  24.000       Kochi         Python  32000.0        NaT
6    NaN  25.000     Calicut   Data Science  35000.0 2025-01-03
7  Meera  23.000     Calicut         Python  30000.0        NaT

In [88]:
df['Join_Date']=df['Join_Date'].fillna(df['Join_Date'].mode()[0])

In [89]:
df

    Name     Age        City         Course   Salary  Join_Date
0  Rahul  22.000       Kochi   Data Science  25000.0 2025-10-01
1  Priya  23.000       Kochi   Data Science  30000.0 2025-10-01
2  Arjun  22.875       Kochi   Data Science  28000.0 2025-05-02
3  Sneha  21.000  Trivandrum         Python  29375.0 2025-10-01
4  Rahul  22.000     Unknown  Not Specified  25000.0 2025-10-01
5  Akhil  24.000       Kochi         Python  32000.0 2025-10-01
6    NaN  25.000     Calicut   Data Science  35000.0 2025-01-03
7  Meera  23.000     Calicut         Python  30000.0 2025-10-01

In [90]:
#5. complete data cleaning
#inspect the data
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       7 non-null      str
 1   Age        8 non-null      float64
 2   City       8 non-null      str
 3   Course     8 non-null      str
 4   Salary     8 non-null      float64
 5   Join_Date  8 non-null      datetime64[us]
dtypes: datetime64[us](1), float64(2), str(3)
memory usage: 516.0 bytes

In [92]:
#clean string values
df['Name']=df['Name'].fillna('Unknown').str.strip().str.title()
df['City']=df['City'].fillna('Unknown').str.strip().str.title()
df['Course']=df['Course'].fillna('Not Specified').str.strip().str.title()

In [93]:
df

      Name     Age        City         Course   Salary  Join_Date
0    Rahul  22.000       Kochi   Data Science  25000.0 2025-10-01
1    Priya  23.000       Kochi   Data Science  30000.0 2025-10-01
2    Arjun  22.875       Kochi   Data Science  28000.0 2025-05-02
3    Sneha  21.000  Trivandrum         Python  29375.0 2025-10-01
4    Rahul  22.000     Unknown  Not Specified  25000.0 2025-10-01
5    Akhil  24.000       Kochi         Python  32000.0 2025-10-01
6  Unknown  25.000     Calicut   Data Science  35000.0 2025-01-03
7    Meera  23.000     Calicut         Python  30000.0 2025-10-01

In [94]:
#handling missing values
df.isnull().sum()

Name         0
Age          0
City         0
Course       0
Salary       0
Join_Date    0
dtype: int64

No null values exist

In [95]:
#removing duplicate rows
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
dtype: bool

No more duplicate rows exists

NO DUPLICATED OR MISSING VALUES REMAINING HENCE THE DATASET IS CLEANED

In [ ]:
# DISPLAYING FINAL CLEANED DATASET
df

      Name     Age        City         Course   Salary  Join_Date
0    Rahul  22.000       Kochi   Data Science  25000.0 2025-10-01
1    Priya  23.000       Kochi   Data Science  30000.0 2025-10-01
2    Arjun  22.875       Kochi   Data Science  28000.0 2025-05-02
3    Sneha  21.000  Trivandrum         Python  29375.0 2025-10-01
4    Rahul  22.000     Unknown  Not Specified  25000.0 2025-10-01
5    Akhil  24.000       Kochi         Python  32000.0 2025-10-01
6  Unknown  25.000     Calicut   Data Science  35000.0 2025-01-03
7    Meera  23.000     Calicut         Python  30000.0 2025-10-01