In [30]:
import numpy as np

In [31]:
import pandas as pd
data={
    'Name':['Anu','Rahul','Akhil','Meera','Neha','Arjun'],
    'Age':[23,np.nan,25,24,np.nan,27],
    'City':['Kochi','Calicut',np.nan,'Kochi','Thrissur','Kochi'],
    'Salary':[25000,30000,35000,np.nan,28000,40000],
    'Department':['IT','HR','IT','Finance','HR',np.nan]
}

In [32]:
#create the above dataframe
#display the dataframe
df=pd.DataFrame(data)
df

    Name   Age      City   Salary Department
0    Anu  23.0     Kochi  25000.0         IT
1  Rahul   NaN   Calicut  30000.0         HR
2  Akhil  25.0       NaN  35000.0         IT
3  Meera  24.0     Kochi      NaN    Finance
4   Neha   NaN  Thrissur  28000.0         HR
5  Arjun  27.0     Kochi  40000.0        NaN

In [33]:
#check the number of null value in each column
df.isna().sum()

Name          0
Age           2
City          1
Salary        1
Department    1
dtype: int64

In [34]:
#display rows containing null values
df[df.isna().any(axis=1)]

    Name   Age      City   Salary Department
1  Rahul   NaN   Calicut  30000.0         HR
2  Akhil  25.0       NaN  35000.0         IT
3  Meera  24.0     Kochi      NaN    Finance
4   Neha   NaN  Thrissur  28000.0         HR
5  Arjun  27.0     Kochi  40000.0        NaN

In [40]:
#replace null value in age with mean age
df['Age']=df['Age'].fillna(df['Age'].mean())
df

    Name    Age      City   Salary    Department
0    Anu  23.00     Kochi  25000.0            IT
1  Rahul  24.75   Calicut  30000.0            HR
2  Akhil  25.00   Unknown  35000.0            IT
3  Meera  24.00     Kochi  30000.0       Finance
4   Neha  24.75  Thrissur  28000.0            HR
5  Arjun  27.00     Kochi  40000.0  Not Assigned

In [41]:
#replace null value in city with 'unknown'
df['City']=df['City'].fillna('Unknown')
df

    Name    Age      City   Salary    Department
0    Anu  23.00     Kochi  25000.0            IT
1  Rahul  24.75   Calicut  30000.0            HR
2  Akhil  25.00   Unknown  35000.0            IT
3  Meera  24.00     Kochi  30000.0       Finance
4   Neha  24.75  Thrissur  28000.0            HR
5  Arjun  27.00     Kochi  40000.0  Not Assigned

In [42]:
#replace null value in salary with the median salary
df['Salary']=df['Salary'].fillna(df['Salary'].median())
df

    Name    Age      City   Salary    Department
0    Anu  23.00     Kochi  25000.0            IT
1  Rahul  24.75   Calicut  30000.0            HR
2  Akhil  25.00   Unknown  35000.0            IT
3  Meera  24.00     Kochi  30000.0       Finance
4   Neha  24.75  Thrissur  28000.0            HR
5  Arjun  27.00     Kochi  40000.0  Not Assigned

In [39]:
#replace null value in department with 'not assigned'
df['Department']=df['Department'].fillna('Not Assigned')
df

    Name   Age      City   Salary    Department
0    Anu  23.0     Kochi  25000.0            IT
1  Rahul   NaN   Calicut  30000.0            HR
2  Akhil  25.0   Unknown  35000.0            IT
3  Meera  24.0     Kochi  30000.0       Finance
4   Neha   NaN  Thrissur  28000.0            HR
5  Arjun  27.0     Kochi  40000.0  Not Assigned

In [ ]:
#checking null values again
df.isna().sum()

Name          0
Age           0
City          0
Salary        0
Department    0
dtype: int64

In [ ]:
#final cleared dataframe
df

    Name    Age      City   Salary    Department
0    Anu  23.00     Kochi  25000.0            IT
1  Rahul  24.75   Calicut  30000.0            HR
2  Akhil  25.00   Unknown  35000.0            IT
3  Meera  24.00     Kochi  30000.0       Finance
4   Neha  24.75  Thrissur  28000.0            HR
5  Arjun  27.00     Kochi  40000.0  Not Assigned